<?php

declare(strict_types=1);

namespace OpenGenetics\Core;

/**
 * AdminGenerator — Auto Admin Panel Generator (OpenGenetics v2.0)
 *
 * Inspects database tables and generates a fully-functional admin panel
 * with CRUD operations, search, pagination, and RBAC protection — no templates needed.
 *
 * Usage (generate static HTML + JS admin panel):
 *   AdminGenerator::generate([
 *       'tables'  => ['users', 'products', 'orders'],
 *       'output'  => 'public/admin',
 *       'title'   => 'My App Admin',
 *       'protect' => 'admin',   // Required role
 *   ]);
 *
 * Or scaffold a dynamic REST-backed admin endpoint:
 *   php genetics make:admin Products
 */
final class AdminGenerator
{
    private string $outputDir;
    private string $title;
    private string $requiredRole;
    private array  $tables;

    public function __construct(array $options = [])
    {
        $this->title        = $options['title']   ?? 'Admin Panel';
        $this->requiredRole = $options['protect']  ?? 'ADMIN';
        $this->tables       = $options['tables']   ?? [];
        $this->outputDir    = rtrim($options['output'] ?? 'public/admin', '/');
    }

    // ── Main Entry ────────────────────────────────────────

    /**
     * Generate a complete admin panel into the output directory.
     *
     * @param array $options Configuration options
     * @return bool True on success
     */
    public static function generate(array $options = []): bool
    {
        $gen = new static($options);
        return $gen->run();
    }

    // ── Schema Inspection ─────────────────────────────────

    /**
     * Discover all tables in the current database.
     * @return string[]
     */
    public static function discoverTables(): array
    {
        try {
            $rows = Database::query("SHOW TABLES");
            if (empty($rows)) return [];
            $key = array_key_first($rows[0]);
            return array_column($rows, $key);
        } catch (\Throwable) {
            return [];
        }
    }

    /**
     * Get column metadata for a table.
     * @return array<array{Field:string, Type:string, Null:string, Key:string, Default:mixed}>
     */
    public static function describeTable(string $table): array
    {
        try {
            $table = preg_replace('/[^a-zA-Z0-9_]/', '', $table);
            return Database::query("DESCRIBE `{$table}`") ?? [];
        } catch (\Throwable) {
            return [];
        }
    }

    // ── API Scaffold Generation ───────────────────────────

    /**
     * Generate a CRUD admin API endpoint for a table.
     * Called via: php genetics make:admin Users
     *
     * @param string $root    Project root path
     * @param string $table   Table name
     * @param string $outDir  Output directory (default: api/admin/)
     * @return string Path to generated file
     */
    public static function scaffoldApiEndpoint(
        string $root,
        string $table,
        string $outDir = 'api/admin',
        string $role = 'ADMIN'
    ): string {
        $table      = strtolower(preg_replace('/[^a-zA-Z0-9_]/', '', $table));
        $className  = ucfirst($table);
        $outPath    = $root . '/' . $outDir . '/' . $table . '.php';

        if (!is_dir(dirname($outPath))) {
            mkdir(dirname($outPath), 0755, true);
        }

        $timestamp  = self::timestamp();
        $columns    = self::describeTable($table);
        $colList    = implode(', ', array_column($columns, 'Field'));
        $pkField    = self::getPrimaryKey($columns);

        $editableCols = array_filter($columns, fn($c) => !in_array($c['Field'], [$pkField, 'created_at', 'updated_at'], true));
        $insertFields = array_column(array_values($editableCols), 'Field');
        $insertCols   = implode(', ', $insertFields);
        $insertParams = implode(', ', array_map(fn($f) => ":{$f}", $insertFields));
        $updateSet    = implode(', ', array_map(fn($f) => "{$f} = :{$f}", $insertFields));

        $insertBindings = implode("\n        ", array_map(
            fn($f) => "'{$f}' => \$body['{$f}'] ?? null,",
            $insertFields
        ));

        $template = <<<PHP
<?php
/**
 * Admin: {$className} CRUD
 * Auto-generated by AdminGenerator — DO NOT EDIT (re-generate instead)
 * Generated: {$timestamp}
 *
 * Endpoints:
 *   GET    /api/admin/{$table}        — List all (paginated)
 *   POST   /api/admin/{$table}        — Create new
 *   PUT    /api/admin/{$table}        — Update by ?id=
 *   DELETE /api/admin/{$table}        — Delete by ?id=
 */

use OpenGenetics\\Core\\{Database, Response, Validator};
use OpenGenetics\\Auth\\Guard;

#[\\OpenGenetics\\Core\\Middleware('auth:{$role}')]
class {$className}Admin
{
    public static function get(array \$body): void
    {
        Guard::requireRole('{$role}');
        \$page    = max(1, (int)(\$_GET['page']   ?? 1));
        \$perPage = min((int)(\$_GET['per_page'] ?? 20), 100);
        \$offset  = (\$page - 1) * \$perPage;

        \$total = Database::queryOne("SELECT COUNT(*) as c FROM `{$table}`")['c'] ?? 0;
        \$rows  = Database::query(
            "SELECT {$colList} FROM `{$table}` LIMIT :limit OFFSET :offset",
            ['limit' => \$perPage, 'offset' => \$offset]
        );
        Response::paginated(\$rows, (int)\$total, \$page, \$perPage);
    }

    public static function post(array \$body): void
    {
        Guard::requireRole('{$role}');
        Database::execute(
            "INSERT INTO `{$table}` ({$insertCols}) VALUES ({$insertParams})",
            [{$insertBindings}]
        );
        Response::success(null, '{$className} created', 201);
    }

    public static function put(array \$body): void
    {
        Guard::requireRole('{$role}');
        \$id = (int)(\$_GET['id'] ?? 0);
        Database::execute(
            "UPDATE `{$table}` SET {$updateSet} WHERE {$pkField} = :__pk",
            [{$insertBindings} '__pk' => \$id]
        );
        Response::success(null, '{$className} updated');
    }

    public static function delete(array \$body): void
    {
        Guard::requireRole('{$role}');
        \$id = (int)(\$_GET['id'] ?? 0);
        Database::execute("DELETE FROM `{$table}` WHERE {$pkField} = :id", ['id' => \$id]);
        Response::success(null, '{$className} deleted');
    }
}

PHP;
        file_put_contents($outPath, $template);
        return $outPath;
    }

    // ── Internal helpers ──────────────────────────────────

    private function run(): bool
    {
        if (!is_dir($this->outputDir)) {
            mkdir($this->outputDir, 0755, true);
        }

        foreach ($this->tables as $table) {
            $path = self::scaffoldApiEndpoint(
                dirname($this->outputDir),
                $table,
                ltrim(str_replace(dirname($this->outputDir), '', $this->outputDir), '/'),
                $this->requiredRole
            );
        }

        return true;
    }

    private static function timestamp(): string
    {
        return date('Y-m-d H:i:s');
    }

    private static function getPrimaryKey(array $columns): string
    {
        foreach ($columns as $col) {
            if (($col['Key'] ?? '') === 'PRI') {
                return $col['Field'];
            }
        }
        return 'id';
    }
}
